import type { Metadata } from "next";
import {
  Averia_Serif_Libre,
  Cabin,
  Candal,
  Capriola,
  Caveat_Brush,
  Darumadrop_One,
  Days_One,
  Genos,
  Happy_Monkey,
  Instrument_Sans,
  Inter,
  Judson,
  Kanit,
  Karla,
  Merienda,
  Mooli,
  Oxygen,
} from "next/font/google";
import "./globals.css";

const happyMonkey = Happy_Monkey({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-happy-monkey",
});

const cabin = Cabin({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-cabin",
});

const capriola = Capriola({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-capriola",
});

const caveatBrush = Caveat_Brush({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-caveat-brush",
});

const inter = Inter({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-inter",
});

const karla = Karla({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-karla",
});

const oxygen = Oxygen({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  variable: "--font-oxygen",
});

const averiaSerifLibre = Averia_Serif_Libre({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-averia-serif-libre",
});

const mooli = Mooli({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-mooli",
});

const kanit = Kanit({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-kanit",
});

const daysOne = Days_One({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-days-one",
});

const instrumentSans = Instrument_Sans({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-instrument-sans",
});

const merienda = Merienda({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-merienda",
});

const candal = Candal({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-candal",
});

const judson = Judson({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-judson",
});

const darumadropOne = Darumadrop_One({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-darumadrop-one",
});

const genos = Genos({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-genos",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${happyMonkey.variable} ${cabin.variable} ${capriola.variable} ${caveatBrush.variable} ${inter.variable} ${karla.variable} ${oxygen.variable} ${averiaSerifLibre.variable} ${mooli.variable} ${kanit.variable} ${daysOne.variable} ${instrumentSans.variable} ${merienda.variable} ${candal.variable} ${judson.variable} ${darumadropOne.variable} ${genos.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
