import type { Metadata } from "next";
import {
  Cabin,
  Capriola,
  Caveat_Brush,
  Happy_Monkey,
  Inter,
  Karla,
  Oxygen,
} from "next/font/google";
import "./globals.css";

const happyMonkey = Happy_Monkey({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-happy-monkey",
});

const cabin = Cabin({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-cabin",
});

const capriola = Capriola({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-capriola",
});

const caveatBrush = Caveat_Brush({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-caveat-brush",
});

const inter = Inter({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-inter",
});

const karla = Karla({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-karla",
});

const oxygen = Oxygen({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  variable: "--font-oxygen",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${happyMonkey.variable} ${cabin.variable} ${capriola.variable} ${caveatBrush.variable} ${inter.variable} ${karla.variable} ${oxygen.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
